# Generated by Django 3.1.6 on 2021-03-09 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BTC_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_updated', models.DateTimeField(verbose_name='last updated')),
                ('btc_price', models.FloatField(verbose_name='btc price')),
            ],
        ),
    ]
